/* SHOP 商品カタログ（ダミーデータ） */
window.PRODUCTS = [
 {
  "id": "app1",
  "cat": "APPAREL",
  "name": "VΛNT LOGO HOODIE / BLACK",
  "price": 8800,
  "img": "./apparel1-mtrjbpj4-qbd8.png",
  "size": "S / M / L / XL",
  "color": "BLACK",
  "mat": "綿 90% / ポリエステル 10%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "裏起毛のヘビーウェイト。ステージでも街でも着られる一枚。",
  "lead": "胸に小さくシェブロン、背面にロゴ。重さのある生地で、踊ったときのシルエットを想定した裁断。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app2",
  "cat": "APPAREL",
  "name": "VΛNT LOGO TEE / BLACK",
  "price": 4800,
  "img": "./apparel2-mtrii3xt-vf4g.png",
  "size": "S / M / L / XL",
  "color": "BLACK",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "毎日着られる厚さのベーシックTEE。",
  "lead": "肩の可動を邪魔しない身幅と、洗ってもよれない首リブ。プリントは控えめなマットインク。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app3",
  "cat": "APPAREL",
  "name": "VΛNT CHEVRON TEE / WHITE",
  "price": 4800,
  "img": "./apparel3-mtrihz8n-np7w.png",
  "size": "S / M / L / XL",
  "color": "WHITE",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "毎日着られる厚さのベーシックTEE。",
  "lead": "肩の可動を邪魔しない身幅と、洗ってもよれない首リブ。プリントは控えめなマットインク。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app4",
  "cat": "APPAREL",
  "name": "VΛNT L/S SHIRT / WHITE",
  "price": 7800,
  "img": "./apparel4-mtrihqih-8cbq.png",
  "size": "S / M / L / XL",
  "color": "WHITE",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "一枚でも重ね着でも成立する長袖シャツ。",
  "lead": "袖を通したときの落ち感を優先した薄手の天竺。袖口とネックはリブで締めています。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app5",
  "cat": "APPAREL",
  "name": "VΛNT LOGO CAP / BLACK",
  "price": 4800,
  "img": "./apparel5-mtrihkxv-8mjt.png",
  "size": "FREE（55–59CM / アジャスター付き）",
  "color": "BLACK",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "浅すぎない被り心地のロゴキャップ。",
  "lead": "前面に刺繍のシェブロン。汗をかいても型が落ちにくい芯地を入れています。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app6",
  "cat": "APPAREL",
  "name": "ΛLLY LOGO HOODIE / WHITE",
  "price": 8800,
  "img": "./apparel6-mtrjbv5o-uw31.png",
  "size": "S / M / L / XL",
  "color": "WHITE",
  "mat": "綿 90% / ポリエステル 10%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "裏起毛のヘビーウェイト。ステージでも街でも着られる一枚。",
  "lead": "胸に小さくシェブロン、背面にロゴ。重さのある生地で、踊ったときのシルエットを想定した裁断。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app7",
  "cat": "APPAREL",
  "name": "ΛLLY LOGO TEE / BLACK",
  "price": 4800,
  "img": "./apparel7-mtrie6ml-i1m6.png",
  "size": "S / M / L / XL",
  "color": "BLACK",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "毎日着られる厚さのベーシックTEE。",
  "lead": "肩の可動を邪魔しない身幅と、洗ってもよれない首リブ。プリントは控えめなマットインク。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app8",
  "cat": "APPAREL",
  "name": "ΛLLY CHEVRON TEE / WHITE",
  "price": 4800,
  "img": "./apparel8-mtrie0zj-dm1t.png",
  "size": "S / M / L / XL",
  "color": "WHITE",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "毎日着られる厚さのベーシックTEE。",
  "lead": "肩の可動を邪魔しない身幅と、洗ってもよれない首リブ。プリントは控えめなマットインク。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app9",
  "cat": "APPAREL",
  "name": "ΛLLY L/S SHIRT / BLACK",
  "price": 7800,
  "img": "./apparel9-mtridtyf-hc1s.png",
  "size": "S / M / L / XL",
  "color": "BLACK",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "一枚でも重ね着でも成立する長袖シャツ。",
  "lead": "袖を通したときの落ち感を優先した薄手の天竺。袖口とネックはリブで締めています。",
  "sizes": [
   "S",
   "M",
   "L",
   "XL"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "app10",
  "cat": "APPAREL",
  "name": "ΛLLY LOGO CAP / BLACK",
  "price": 4800,
  "img": "./apparel10-mtridkzy-zrj3.png",
  "size": "FREE（55–59CM / アジャスター付き）",
  "color": "BLACK",
  "mat": "綿 100%",
  "ship": "受注生産 / 2026.10 上旬",
  "desc": "浅すぎない被り心地のロゴキャップ。",
  "lead": "前面に刺繍のシェブロン。汗をかいても型が落ちにくい芯地を入れています。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "goo1",
  "cat": "GOODS",
  "name": "ACRYLIC KEYCHAIN (3 TYPES)",
  "price": 1500,
  "img": "./goods1-mtrfvtri-59fg.png",
  "size": "約 60 × 60 MM",
  "color": "3 TYPES",
  "mat": "アクリル 3MM",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "メンバー3種のアクリルキーチェーン。",
  "lead": "鍵にもバッグにも付けやすいサイズ。裏面までフルカラーでプリントしています。",
  "sizes": [],
  "variants": [
   "WAKA",
   "INA",
   "KUMA"
  ],
  "variantLabel": "TYPE — 種類"
 },
 {
  "id": "goo2",
  "cat": "GOODS",
  "name": "STICKER SHEET (10 TYPES)",
  "price": 1200,
  "img": "./goods2-mtrfw3fm-j9zw.png",
  "size": "A5 シート / 10種",
  "color": "10 TYPES",
  "mat": "PVC（耐水）",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "ロゴとメンバーマークの10種セット。",
  "lead": "貼って剥がせるタイプ。スマホケースや水筒に貼れる耐水仕様です。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "goo3",
  "cat": "GOODS",
  "name": "VΛNT PLAYING CARDS",
  "price": 2200,
  "img": "./goods3-mtrfw8bs-n9z3.png",
  "size": "ポーカーサイズ / 54枚",
  "color": "",
  "mat": "紙（エンボス加工）",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "全カードにVΛNTのビジュアルを配置。",
  "lead": "ジョーカー2枚を含む54枚。ケースもロゴ入りのオリジナルです。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "goo4",
  "cat": "GOODS",
  "name": "CAN BADGE SET (4 TYPES)",
  "price": 600,
  "img": "./goods4-mtrfwch7-rwlc.png",
  "size": "直径 56MM / 4種",
  "color": "4 TYPES",
  "mat": "ブリキ / 樹脂",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "定番サイズの缶バッジ4個セット。",
  "lead": "ライブに持って行きたくなる大きさ。バラ売りはなくセットのみです。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "goo5",
  "cat": "GOODS",
  "name": "SMARTPHONE CASE (5 TYPES)",
  "price": 3500,
  "img": "./goods5-mtrfwvme-zs49.png",
  "size": "5機種 / 各1種",
  "color": "5 TYPES",
  "mat": "ポリカーボネート / TPU",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "背面に大きくシェブロンを配置。",
  "lead": "側面はやわらかいTPU、背面は硬質。落としても衝撃を受け止める二層構造。",
  "sizes": [],
  "variants": [
   "WAKA",
   "INA",
   "KUMA",
   "BLACK",
   "CLEAR"
  ],
  "variantLabel": "TYPE — 種類"
 },
 {
  "id": "goo6",
  "cat": "GOODS",
  "name": "CHIBI PLUSH DOLL (3 TYPES)",
  "price": 2800,
  "img": "./goods6-mtrfx0iq-lsfe.png",
  "size": "全高 約 15CM / 3種",
  "color": "3 TYPES",
  "mat": "ポリエステル 100%",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "メンバー3種のちびぬいぐるみ。",
  "lead": "手に持ったときの重さまで調整した小さめサイズ。衣装はステージ衣装をベースにしています。",
  "sizes": [],
  "variants": [
   "WAKA",
   "INA",
   "KUMA"
  ],
  "variantLabel": "TYPE — 種類"
 },
 {
  "id": "goo7",
  "cat": "GOODS",
  "name": "VΛNT LOGO MUG / BLACK",
  "price": 2800,
  "img": "./goods7-mtrfxz8a-nz1n.png",
  "size": "容量 320ML",
  "color": "BLACK",
  "mat": "陶器",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "毎朝つかえるロゴマグ。",
  "lead": "厚みのある陶器で、持ったときに手にしっくりくる形。電子レンジ・食洗機対応。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "goo8",
  "cat": "GOODS",
  "name": "VΛNT FACE TOWEL / BLACK",
  "price": 1800,
  "img": "./goods8-mtrfy450-ri1l.png",
  "size": "34 × 80 CM",
  "color": "BLACK",
  "mat": "綿 100%",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "ライブでも使えるフェイスタオル。",
  "lead": "首に掛けたときにずれない長さ。端のロゴは織りで入れています。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "goo9",
  "cat": "GOODS",
  "name": "ΛLLY LOGO MUG / WHITE",
  "price": 2800,
  "img": "./goods9-mtrfy8bb-22q7.png",
  "size": "容量 320ML",
  "color": "WHITE",
  "mat": "陶器",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "毎朝つかえるロゴマグ。",
  "lead": "厚みのある陶器で、持ったときに手にしっくりくる形。電子レンジ・食洗機対応。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "goo10",
  "cat": "GOODS",
  "name": "ΛLLY FACE TOWEL / WHITE",
  "price": 1800,
  "img": "./goods10-mtrfyhz8-efll.png",
  "size": "34 × 80 CM",
  "color": "WHITE",
  "mat": "綿 100%",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "ライブでも使えるフェイスタオル。",
  "lead": "首に掛けたときにずれない長さ。端のロゴは織りで入れています。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "acc1",
  "cat": "ACCESSORY",
  "name": "ΛLLY PENDANT NECKLACE",
  "price": 6800,
  "img": "./5-mtre3y2v-9890.png",
  "size": "チェーン 50CM（アジャスター付き）",
  "color": "SILVER",
  "mat": "SILVER 925",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "シェブロンをかたどったペンダント。",
  "lead": "服の上からでも沈まない厚み。チェーンは長さを2段階で変えられます。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "acc2",
  "cat": "ACCESSORY",
  "name": "CHEVRON EARRINGS / SILVER",
  "price": 4800,
  "img": "./3-mtre42w9-zhqz.png",
  "size": "FREE / 1ペア（全長 約 28MM）",
  "color": "SILVER",
  "mat": "SILVER 925",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "揺れの見え方を計算したシェブロンのピアス。",
  "lead": "踊ったときの揺れ幅を抑えた軽さ。ポストもシルバー925です。",
  "sizes": [],
  "variants": [
   "ピアス（リング式）",
   "ピアス（直結式）",
   "イヤリング（クリップ式・微調整可）",
   "イヤリング（クリップ式）",
   "イヤリング（プライヤリング）"
  ],
  "variantLabel": "金具 — TYPE（全5種）"
 },
 {
  "id": "acc3",
  "cat": "ACCESSORY",
  "name": "ΛLLY SIGNET RING",
  "price": 5800,
  "img": "./7-mtre4m5p-9lnx.png",
  "size": "9 / 11 / 13 / 15 号",
  "color": "SILVER",
  "mat": "SILVER 925",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "印台にロゴを刻んだシグネットリング。",
  "lead": "角を落とした印台で、指に当たる縁がやわらか。刻印は深めに入れています。",
  "sizes": [
   "9号",
   "11号",
   "13号",
   "15号"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "acc4",
  "cat": "ACCESSORY",
  "name": "ΛLLY CHARM KEYRING",
  "price": 2200,
  "img": "./accessory8-mtrid7ae-bs8h.png",
  "size": "チャーム 約 30MM",
  "color": "",
  "mat": "真鍮 / シルバー仕上げ",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "鍵にもバッグにも付くチャーム。",
  "lead": "落ちにくい二重リング。使うほどに角が馴染むシルバー仕上げです。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "acc5",
  "cat": "ACCESSORY",
  "name": "VΛNT PENDANT NECKLACE",
  "price": 6800,
  "img": "./6-mtre4yke-8sd5.png",
  "size": "チェーン 50CM（アジャスター付き）",
  "color": "SILVER",
  "mat": "SILVER 925",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "シェブロンをかたどったペンダント。",
  "lead": "服の上からでも沈まない厚み。チェーンは長さを2段階で変えられます。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "acc6",
  "cat": "ACCESSORY",
  "name": "VΛNT DROP EARRINGS",
  "price": 4800,
  "img": "./4-mtre55i7-0ma9.png",
  "size": "全長 約 28MM / 1ペア",
  "color": "SILVER",
  "mat": "SILVER 925",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "揺れの見え方を計算したドロップ型。",
  "lead": "踊ったときの揺れ幅を抑えた軽さ。ポストもシルバー925です。",
  "sizes": [],
  "variants": [
   "ピアス（リング式）",
   "ピアス（直結式）",
   "イヤリング（クリップ式・微調整可）",
   "イヤリング（クリップ式）",
   "イヤリング（プライヤリング）"
  ],
  "variantLabel": "金具 — TYPE（全5種）"
 },
 {
  "id": "acc7",
  "cat": "ACCESSORY",
  "name": "VΛNT SIGNET RING",
  "price": 5800,
  "img": "./8-mtre5g12-t5q7.png",
  "size": "9 / 11 / 13 / 15 号",
  "color": "SILVER",
  "mat": "SILVER 925",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "印台にロゴを刻んだシグネットリング。",
  "lead": "角を落とした印台で、指に当たる縁がやわらか。刻印は深めに入れています。",
  "sizes": [
   "9号",
   "11号",
   "13号",
   "15号"
  ],
  "variants": [],
  "variantLabel": ""
 },
 {
  "id": "acc8",
  "cat": "ACCESSORY",
  "name": "VΛNT CHARM KEYRING",
  "price": 2200,
  "img": "./1-mtre77j4-mr9s.png",
  "size": "チャーム 約 30MM",
  "color": "",
  "mat": "真鍮 / シルバー仕上げ",
  "ship": "通常配送 / 2026.09 中旬",
  "desc": "鍵にもバッグにも付くチャーム。",
  "lead": "落ちにくい二重リング。使うほどに角が馴染むシルバー仕上げです。",
  "sizes": [],
  "variants": [],
  "variantLabel": ""
 }
];
